[project]
name = "crew-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.4",
    "crewai-tools>=0.62.0",
    "crewai[tools]>=0.159.0",
    "duckduckgo-search>=8.1.1",
    "embedchain>=0.1.128",
]
